language: python
python:
  - "2.7"
sudo: false
install: 
  - pip install -e .
  - pip install coveralls
before_script:
  - evennia --init dummy
  - cd dummy
  - evennia migrate
script:
  - coverage run --source=../evennia --omit=*/migrations/*,*/urls.py,*/test*.py,*.sh,*.txt,*.md,*.pyc,*.service ../bin/unix/evennia test evennia  
after_success:
  - coveralls
